name: cardio_upstream
source: local
task: multilabel
normalization: standard
normalizer_path: '/path/normalizer.pkl'
data_path: '/path/'
out_path: '/path/output/'
stage: 'pretrain'
full_model: false
train: false
y_policy:
