name: efficientPS_env
channels:
  - defaults
dependencies:
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cython=0.29.21
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.7.9
  - readline=8.0
  - setuptools=51.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.11.0
    - addict==2.4.0
    - appdirs==1.4.4
    - attrs==20.3.0
    - cachetools==4.2.0
    - chardet==4.0.0
    - cityscapesscripts==2.2.0
    - coloredlogs==15.0
    - cycler==0.10.0
    - decorator==4.4.2
    - future==0.18.2
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.34.0
    - humanfriendly==9.1
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==3.4.0
    - iniconfig==1.1.1
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.3.3
    - mmcv==0.5.9
    - networkx==2.5
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - packaging==20.8
    - pandas==1.2.0
    - pillow==6.2.2
    - pluggy==0.13.1
    - protobuf==3.14.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pyquaternion==0.9.9
    - pytest==6.2.1
    - python-dateutil==2.8.1
    - pytz==2020.5
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - scikit-image==0.18.1
    - scipy==1.6.0
    - seaborn==0.11.1
    - six==1.15.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - terminaltables==3.1.0
    - tifffile==2021.1.14
    - toml==0.10.2
    - tqdm==4.56.0
    - typing==3.7.4.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - xdoctest==0.15.0
    - yapf==0.30.0
    - zipp==3.4.0
